#!/usr/bin/env bash

set -e

if [ ! -f .git/hooks/pre-commit ]; then
    echo "Installing pre-commit hook"
    cp config/hooks/pre-commit-stub .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit
fi

